# theme settings
theme                    : "minimal-mistakes-jekyll"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"

# Site Settings
locale: "en-US"
title: "International Forum for CV in EEB"
title_separator: "-"
subtitle: "September 18th - 22nd 2023, Lund, Sweden"
# name: "Forum for Computer Vision in EEB"
# description: "Forum for Computer Vision in EEB"
words_per_minute: 200
github: [metadata]
# twitter:
  # username: theasellus
  
# Build settings
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-seo-tag
  - jemoji

titles_from_headings:
  enabled:     false
  strip_title: true
  collections: true 
  
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)
     

include:
  - .htaccess
  - _pages
  
exclude:
  - /local
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
  
keep_files:
  - .git
  - .svn
  
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

permalink: /news/:slug

## defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
